import { jsPDF } from "jspdf"
import QRCode from "qrcode"
import { normalizeStatus } from "./status-utils"

interface CertificateData {
  filename: string
  fileHash: string
  status: string
  txHash: string
  notaryWallet: string
  ownerWallet: string
  timestamp?: string
  documentSummary?: string
}

export async function generateCertificatePDF(data: CertificateData) {
  // Initialize A4 PDF
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  })

  // Theme Colors
  const primaryColor = [15, 23, 42] // Slate 900
  const secondaryColor = [100, 116, 139] // Slate 500
  const accentColor = [16, 185, 129] // Emerald 500

  // 1. Header Section
  doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2])
  doc.rect(0, 0, 210, 40, "F")
  
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(24)
  doc.setFont("helvetica", "bold")
  doc.text("BBSNS Notarization Certificate", 105, 22, { align: "center" })
  
  doc.setFontSize(10)
  doc.setFont("helvetica", "normal")
  doc.text("Blockchain Based Secure Notarization System", 105, 30, { align: "center" })

  // 2. Status Badge
  const s = normalizeStatus(data.status)
  const isApproved = s === "APPROVED" || s === "KYC_VERIFIED"
  if (isApproved) {
    doc.setFillColor(accentColor[0], accentColor[1], accentColor[2])
    doc.roundedRect(85, 50, 40, 10, 2, 2, "F")
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(12)
    doc.setFont("helvetica", "bold")
    doc.text("VERIFIED", 105, 57, { align: "center" })
  }

  // 3. Document Details
  doc.setTextColor(0, 0, 0)
  doc.setFontSize(14)
  doc.setFont("helvetica", "bold")
  doc.text("Document Details", 20, 75)
  doc.setLineWidth(0.5)
  doc.line(20, 78, 190, 78)

  doc.setFontSize(11)
  let currentY = 88
  const lineSpacing = 10

  const addRow = (label: string, value: string, isHash = false) => {
    doc.setFont("helvetica", "bold")
    doc.text(label, 20, currentY)
    doc.setFont("helvetica", "normal")
    
    if (isHash) {
      // Split long hashes
      const splitValue = doc.splitTextToSize(value, 120)
      doc.text(splitValue, 70, currentY)
      currentY += (splitValue.length * 5) + 5
    } else {
      doc.text(value, 70, currentY)
      currentY += lineSpacing
    }
  }

  addRow("File Name:", data.filename)
  addRow("SHA-256 Hash:", data.fileHash, true)
  if (data.documentSummary) {
    addRow("Notes:", data.documentSummary, true)
  }
  
  // Format Date
  const dateStr = data.timestamp ? new Date(data.timestamp).toLocaleString() : new Date().toLocaleString()
  addRow("Timestamp:", dateStr)

  // 4. Cryptographic Proof
  currentY += 5
  doc.setFontSize(14)
  doc.setFont("helvetica", "bold")
  doc.text("Cryptographic Proof", 20, currentY)
  doc.line(20, currentY + 3, 190, currentY + 3)
  
  currentY += 13
  doc.setFontSize(11)
  
  addRow("Notary Wallet:", data.notaryWallet || "N/A", true)
  addRow("Owner Wallet:", data.ownerWallet || "N/A", true)
  if (data.txHash) {
    addRow("Blockchain TX:", data.txHash, true)
  }

  // 5. QR Code & Verification
  try {
    const bscScanUrl = data.txHash ? `https://testnet.bscscan.com/tx/${data.txHash}` : `https://bbsns.com/verify?hash=${data.fileHash}`
    const qrDataUrl = await QRCode.toDataURL(bscScanUrl, { margin: 1, width: 100 })
    
    const qrY = currentY + 10
    doc.addImage(qrDataUrl, "PNG", 20, qrY, 40, 40)
    
    // Verification Text
    doc.setFont("helvetica", "italic")
    doc.setFontSize(9)
    doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2])
    const verificationText = "To verify the authenticity of exactly this document, compute the SHA-256 hash of your digital file and compare it to the hash above. Scan the QR code to view the permanent blockchain transaction record on BscScan. Any modification to the original file will break the hash."
    const splitDisclaimer = doc.splitTextToSize(verificationText, 110)
    doc.text(splitDisclaimer, 70, qrY + 10)
    
  } catch (error) {
    console.error("Failed to generate QR code", error)
  }

  // 6. Footer
  doc.setFont("helvetica", "normal")
  doc.setFontSize(8)
  doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2])
  doc.text("Generated by BBSNS - Blockchain Based Secure Notarization System", 105, 285, { align: "center" })
  doc.text("This receipt constitutes immutable, cryptographically verifiable proof.", 105, 290, { align: "center" })

  // Download
  const cleanFilename = data.filename.replace(/[^a-z0-9]/gi, '_').toLowerCase()
  doc.save(`bbsns_certificate_${cleanFilename}.pdf`)
}
